# Generated by Django 4.2.7 on 2023-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
