# Generated by Django 4.2.7 on 2023-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservations', '0001_initial'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reservations',
            field=models.ManyToManyField(to='Reservations.reservation'),
        ),
    ]
