# Generated by Django 4.2.7 on 2023-12-09 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payments', '0001_initial'),
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reserved_On', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_of_Reservation', models.DateTimeField()),
                ('Number_of_People', models.IntegerField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Done', 'Done')], max_length=100)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
                ('Deposit_Paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payments.payment')),
            ],
        ),
    ]
